# Script
day = "HOUSEID,PERSONID,FRSTHM,OUTOFTWN,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,ONTD_P14,ONTD_P15,TDCASEID,HH_HISP,HH_RACE,DRIVER,R_SEX,WORKER,DRVRCNT,HHFAMINC,HHSIZE,HHVEHCNT,NUMADLT,FLAG100,LIF_CYC,TRIPPURP,AWAYHOME,CDIVMSAR,CENSUS_D,CENSUS_R,DROP_PRK,DRVR_FLG,EDUC,ENDTIME,HH_ONTD,HHMEMDRV,HHRESP,HHSTATE,HHSTFIPS,INTSTATE,MSACAT,MSASIZE,NONHHCNT,NUMONTRP,PAYTOLL,PRMACT,PROXY,PSGR_FLG,R_AGE,RAIL,STRTTIME,TRACC1,TRACC2,TRACC3,TRACC4,TRACC5,TRACCTM,TRAVDAY,TREGR1,TREGR2,TREGR3,TREGR4,TREGR5,TREGRTM,TRPACCMP,TRPHHACC,TRPHHVEH,TRPTRANS,TRVL_MIN,TRVLCMIN,TRWAITTM,URBAN,URBANSIZE,URBRUR,USEINTST,USEPUBTR,VEHID,WHODROVE,WHYFROM,WHYTO,WHYTRP1S,WRKCOUNT,DWELTIME,WHYTRP90,TDTRPNUM,TDWKND,TDAYDATE,TRPMILES,WTTRDFIN,VMT_MILE,PUBTRANS,HOMEOWN,HOMETYPE,HBHUR,HTRESDN,HTHTNRNT,HTPPOPDN,HTEEMPDN,HBRESDN,HBHTNRNT,HBPPOPDN,GASPRICE,VEHTYPE,HH_CBSA,HHC_MSA"
house = "HOUSEID,VARSTRAT,WTHHFIN,DRVRCNT,CDIVMSAR,CENSUS_D,CENSUS_R,HH_HISP,HH_RACE,HHFAMINC,HHRELATD,HHRESP,HHSIZE,HHSTATE,HHSTFIPS,HHVEHCNT,HOMEOWN,HOMETYPE,MSACAT,MSASIZE,NUMADLT,RAIL,RESP_CNT,SCRESP,TRAVDAY,URBAN,URBANSIZE,URBRUR,WRKCOUNT,TDAYDATE,FLAG100,LIF_CYC,CNTTDHH,HBHUR,HTRESDN,HTHTNRNT,HTPPOPDN,HTEEMPDN,HBRESDN,HBHTNRNT,HBPPOPDN,HH_CBSA,HHC_MSA"
veh = "HOUSEID,WTHHFIN,VEHID,DRVRCNT,HHFAMINC,HHSIZE,HHVEHCNT,NUMADLT,FLAG100,CDIVMSAR,CENSUS_D,CENSUS_R,HHSTATE,HHSTFIPS,HYBRID,MAKECODE,MODLCODE,MSACAT,MSASIZE,OD_READ,RAIL,TRAVDAY,URBAN,URBANSIZE,URBRUR,VEHCOMM,VEHOWNMO,VEHYEAR,WHOMAIN,WRKCOUNT,TDAYDATE,VEHAGE,PERSONID,HH_HISP,HH_RACE,HOMEOWN,HOMETYPE,LIF_CYC,ANNMILES,HBHUR,HTRESDN,HTHTNRNT,HTPPOPDN,HTEEMPDN,HBRESDN,HBHTNRNT,HBPPOPDN,BEST_FLG,BESTMILE,BEST_EDT,BEST_OUT,FUELTYPE,GSYRGAL,GSCOST,GSTOTCST,EPATMPG,EPATMPGF,EIADMPG,VEHTYPE,HH_CBSA,HHC_MSA"
perv = "HOUSEID,PERSONID,VARSTRAT,WTPERFIN,SFWGT,HH_HISP,HH_RACE,DRVRCNT,HHFAMINC,HHSIZE,HHVEHCNT,NUMADLT,WRKCOUNT,FLAG100,LIF_CYC,CNTTDTR,BORNINUS,CARRODE,CDIVMSAR,CENSUS_D,CENSUS_R,CONDNIGH,CONDPUB,CONDRIDE,CONDRIVE,CONDSPEC,CONDTAX,CONDTRAV,DELIVER,DIARY,DISTTOSC,DRIVER,DTACDT,DTCONJ,DTCOST,DTRAGE,DTRAN,DTWALK,EDUC,EVERDROV,FLEXTIME,FMSCSIZE,FRSTHM,FXDWKPL,GCDWORK,GRADE,GT1JBLWK,HHRESP,HHSTATE,HHSTFIPS,ISSUE,OCCAT,LSTTRDAY,MCUSED,MEDCOND,MEDCOND6,MOROFTEN,MSACAT,MSASIZE,NBIKETRP,NWALKTRP,OUTCNTRY,OUTOFTWN,PAYPROF,PRMACT,PROXY,PTUSED,PURCHASE,R_AGE,R_RELAT,R_SEX,RAIL,SAMEPLC,SCHCARE,SCHCRIM,SCHDIST,SCHSPD,SCHTRAF,SCHTRN1,SCHTRN2,SCHTYP,SCHWTHR,SELF_EMP,TIMETOSC,TIMETOWK,TOSCSIZE,TRAVDAY,URBAN,URBANSIZE,URBRUR,USEINTST,USEPUBTR,WEBUSE,WKFMHMXX,WKFTPT,WKRMHM,WKSTFIPS,WORKER,WRKTIME,WRKTRANS,YEARMILE,YRMLCAP,YRTOUS,DISTTOWK,TDAYDATE,HOMEOWN,HOMETYPE,HBHUR,HTRESDN,HTHTNRNT,HTPPOPDN,HTEEMPDN,HBRESDN,HBHTNRNT,HBPPOPDN,HH_CBSA,HHC_MSA"
all4 = "CDIVMSAR,CENSUS_D,CENSUS_R,DRVRCNT,FLAG100,HBHTNRNT,HBHUR,HBPPOPDN,HBRESDN,HH_CBSA,HHFAMINC,HHSIZE,HHSTATE,HHSTFIPS,HHVEHCNT,HOMEOWN,HOMETYPE,HOUSEID,HTEEMPDN,HTHTNRNT,HTRESDN,LIF_CYC,MSACAT,MSASIZE,NUMADLT,RAIL,TDAYDATE,TDAYDAY,URBAN,URBANSIZE,URBRUR,WRKCOUNT"
dayheaders = day.split(",")
househeaders = house.split(",")
vehheaders = veh.split(",")
pervheaders = perv.split(",")
all4headers = all4.split(",")

headers = {'day': dayheaders, 'house': househeaders, 'veh': vehheaders, 'perv':pervheaders}

print "day compared to house"
for a in dayheaders:
    if a in househeaders and a not in all4headers:
        print a

print "day compared to veh"
for a in dayheaders:
    if a in vehheaders and a not in all4headers:
        print a

print "day compared to perv"
for a in dayheaders:
    if a in pervheaders and a not in all4headers:
        print a

print "house compared to veh"
for a in househeaders:
    if a in vehheaders and a not in all4headers:
        print a

print "house compared to perv"
for a in househeaders:
    if a in pervheaders and a not in all4headers:
        print a

print "veh compared to perv"
for a in vehheaders:
    if a in pervheaders and a not in all4headers:
        print a

print "day and house and veh"
for a in dayheaders:
    if a in househeaders and a in vehheaders and a not in all4headers:
        print a

print "day and house and perv"
for a in dayheaders:
    if a in househeaders and a in pervheaders and a not in all4headers:
        print a

print "day and veh and perv"
for a in dayheaders:
    if a in vehheaders and a in pervheaders and a not in all4headers:
        print a

print "veh and house and perv"
for a in vehheaders:
    if a in househeaders and a in pervheaders and a not in all4headers:
        print a

print "all of them, but not in the repeated variables table?"
for a in vehheaders:
    if a in househeaders and a in pervheaders and a in dayheaders and a not in all4headers:
        print a

#for ak, av in headers.iteritems():
#    for bk, bv in headers.iteritems():
#        if ak != bk:
#            print ak, "compare to", bk 
#            for h in bv:
#                if h in av:
#                    print h
#    
    
